export { image } from './misc/nuxt-image'
export { tailwindcss } from './misc/tailwind'
export { viewport } from './misc/viewport'
export { i18n } from './misc/i18n'
export { landing } from './landing'
